spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/invenza
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true